name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - adwaita-icon-theme=48.0=unix_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.36.0=h3371d22_4
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - boost-cpp=1.82.0=hdb19cb5_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cython=3.1.3=py310ha738802_2
  - dbus=1.13.6=h5008d03_3
  - epoxy=1.5.10=h166bdaf_1
  - expat=2.7.1=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h55d465d_3
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdk-pixbuf=2.42.10=h64b468e_2
  - giflib=5.2.2=hd590300_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=12.2.1=h64f68a2_1
  - gtk3=3.24.21=h0fee60c_7
  - gts=0.7.6=h64030ff_2
  - harfbuzz=10.2.0=hf296adc_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h0b41bf4_3
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.82.0=h109eef0_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libltdl=2.4.3a=h5888daf_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.56.3=hf6914bd_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.5.4=h5888daf_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - nose=1.3.7=py_1006
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.2=h26f9b46_0
  - pango=1.50.7=h0fee60c_1
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h29eaf8c_0
  - poppler=24.09.0=hc52b300_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pygraphviz=1.14=py310h9a1d609_0
  - python=3.10.16=he870216_1
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beartype==0.14.1
      - beautifulsoup4==4.13.4
      - better-abc==0.0.3
      - bleach==6.2.0
      - blinker==1.9.0
      - blosc2==3.3.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.2
      - cox==0.1.post3
      - cycler==0.12.1
      - dash==3.0.4
      - datasets==3.5.1
      - debugpy==1.8.14
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fancy-einsum==0.0.3
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.0.3
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gensim==4.3.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gputil==1.4.0
      - grakel==0.1.10
      - grpcio==1.71.0
      - gspan-mining==0.2.3
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - imagecorruptions==1.1.2
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.36.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - levenshtein==0.27.1
      - line-profiler==4.2.0
      - littleutils==0.2.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - netlsd==1.0.2
      - networkx==3.4.2
      - notebook==7.4.2
      - notebook-shim==0.2.4
      - numexpr==2.10.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - ogb==1.3.6
      - open-clip-torch==2.32.0
      - opencv-python==4.11.0.86
      - outdated==0.2.2
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - plotly==5.19.0
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py3nvml==0.2.7
      - pyarrow==20.0.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pygsp==0.6.1
      - pyparsing==3.2.3
      - pyrcca==0.2
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-levenshtein==0.27.1
      - python-louvain==0.16
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - rapidfuzz==3.14.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.4.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - robustness==1.2.1.post2
      - rpca==0.1.6
      - rpds-py==0.25.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.14.0
      - tables==3.10.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - tifffile==2025.5.10
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - torch-geometric==2.6.1
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tornado==6.5
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformer-lens==2.15.0
      - transformers==4.49.0
      - transformers-stream-generator==0.0.5
      - triton==3.3.0
      - typeguard==4.4.2
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.4.0
      - wadler-lindig==0.1.5
      - wandb==0.19.10
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - wilds==2.0.0
      - wrapt==1.17.3
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.23.0
